import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'
import Image from "next/image";
dayjs.extend(relativeTime)

const CreatePostWizard = () => {
  const { user } = useUser()

  if (!user) return null

  console.log(user)
  return (
    <div className="flex gap-3 w-full">
      <Image src={user.profileImageUrl} alt={`@${user.username || `user`}'s profile picture`} className="w-14 h-14 rounded-full" width={56} height={56} />
      <input type="text" placeholder="type some emojis!" className="bg-transparent grow outline-none p-4" />
      {/* <SignOutButton /> */}
    </div>
  )
};

type postWithUser = RouterOutputs["post"]["getAll"][number];

const PostView = (props: postWithUser) => {
  const { post, author } = props
  return (
    <div key={post.id} className="flex border-b border-slate-400 p-4 gap-3">
      <Image
        src={author?.profilePicture}
        alt={`@${author.username}'s profile picture`}
        className="w-12 h-12 rounded-full align-middle"
        width={56}
        height={56}
      />
      <div className="flex flex-col">
        <div className="flex text-slate-300  gap-2">
          <span className=" font-semibold">@{author?.username}</span>
          {` · `}
          <span className="font-thin">{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span>{post.content}</span>
      </div>

    </div>
  )
}

const Home: NextPage = () => {

  const { data, isLoading } = api.post.getAll.useQuery()
  const user = useUser();

  if (!data || isLoading) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full border-x border-slate-400 md:max-w-2xl" >
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn &&
              <div className="flex justify-center">
                <SignInButton mode="modal">
                  <button className="text-slate-100">Login</button>
                </SignInButton>
              </div>
            }
            {!!user.isSignedIn && <CreatePostWizard />
            }
          </div>
          <div className="flex flex-col">
            {[...data, ...data]?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
